version: '3.8'

services:
  ollama:
    build:
      context: ./assistant
    container_name: pardos-ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./assistant/diag:/app/diag:ro
    restart: unless-stopped
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull llama3:8b &&
             ollama create pardos-assistant -f /app/diag &&
             wait"
    networks:
      - pardos-network
  pardos-backend:
    build:
      context: ./sistemPardo/backend
      dockerfile: Dockerfile
    container_name: pardos-backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "3000:3000"
    networks: [pardos-network]

  pardos-frontend:
    image: nginx:1.27-alpine
    container_name: pardos-frontend
    depends_on:
      - pardos-backend
    volumes:
      - ./sistemPardo/frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks: [pardos-network]

  portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: pardos-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks: [pardos-network]

volumes:
  ollama_data:
  portainer_data:

networks:
  pardos-network:
    driver: bridge
