version: '3.8'

services:
  ollama:
    build:
      context: ./assistant
      dockerfile: Dockerfile
      args:
        # Opcional: fijar versión de Ollama; si no, instala 'latest'
        # OLLAMA_VERSION: "0.3.13"
    container_name: pardos-ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    networks: [pardos-network]

  pardos-backend:
    build:
      context: ./sistemPardo/backend
      dockerfile: Dockerfile
    container_name: pardos-backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks: [pardos-network]

  pardos-frontend:
    image: nginx:1.27-alpine
    container_name: pardos-frontend
    depends_on:
      - pardos-backend
    volumes:
      - ./sistemPardo/frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks: [pardos-network]

  portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: pardos-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks: [pardos-network]

volumes:
  ollama_data:
  portainer_data:

networks:
  pardos-network:
    driver: bridge
