
services:
  pardos-backend:
    build:
      context: ./sistemPardo/backend
    container_name: pardos-backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=${OLLAMA_URL}
    networks:
      - pardos-network

  frontend:
    image: nginx:alpine
    container_name: pardos-frontend
    volumes:
    - ./sistemPardo/frontend:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"  
    depends_on:
      - pardos-backend
    networks:
      - pardos-network

networks:
  pardos-network:
    driver: bridge
