version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: pardos-ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./assistant/diag:/app/diag
    restart: unless-stopped
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull llama3:8b &&
             ollama create pardos-assistant -f /app/diag &&
             wait"
    networks:
      - pardos-network

  pardos-backend:
    build:
      context: ./sistemPardo/backend
    container_name: pardos-backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - pardos-network

  frontend:
    image: nginx:alpine
    container_name: pardos-frontend
    volumes:
      - ./sistemPardo/frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - pardos-backend
    networks:
      - pardos-network

volumes:
  ollama_data:

networks:
  pardos-network:
    driver: bridge